/**************************************************************************************************************************************
Company Name  :Jade Global Inc.
Created Date  :10th February 2018
Interface name:   : dynamicMethodHandlerInterface
**************************************************************************************************************************************/

public interface dynamicMethodHandlerInterface {
    void dynamicMethodHandler(List<Integration_Event__e> newList);
}