public class RecurssionOnOppandAccount {

    public static Boolean isFromMKT_AddPaymentTrigger = true;
    public static Boolean isFromupdateRenewalsOwnerOnAccount = true;
    public static Boolean isFromupdateOwnerRoleMapping  = true;
    public static Boolean isFromcreateTasl= true;
    public static Boolean isFromupdateUserBadgeTag= true;
    public static Boolean isFromaccountB4InsertB4Update = true;
    public static Boolean isFromPopulateSalesancPro= true;
    
    
    
  }